### PR TITLE
Several fixes/improvements for the Docker build steps

### PR DESCRIPTION
**Pull request by gertvdijk**
The main change is to move away from downloading Open-Zwave over plain HTTP without any verification. While I was working on fixing that, took the opportunity to address some other minor concerns I had. :smile: 

Also, please consider removing the separate Dockerfiles for 1.6 / 1.4, as the OZW version is now a build arg. I didn't change that in this PR yet, as I don't know what your build script looks like, seems not included in this repository?

(Feel free to cherry-pick individual changes in case you don't agree to all I changed.)

### CODE REVIEW

**Comment by robertsLando** [comment]
Hi @gertvdijk. Thanks for this! Would you mind edit the build script to use just one Dockerfile? I mean remove `Dockerfile.dev.cross` and take just the `Dockerfile.latest.cross` that could be renamed to `Dockerfile.cross`. The build script is contained in bin directory and is named [build.sh](https://github.com/robertsLando/Zwave2Mqtt-docker/blob/master/bin/build.sh)

If you don't know how to edit it don't worry I can merge this and make it my own. Thanks again for your support :)

**Comment by gertvdijk** [comment]
Yeah, now I see the build script. Will edit it accordingly.  :-)

I see some more low hanging fruit there; please let me take a day or so to do some edits and tests for it.

**Comment by gertvdijk** [comment]
Done. My quick tests show it is still working, but I fully test with the `createManifest()` part, but that shouldn't have changed much.

**Comment by robertsLando** [comment]
@gertvdijk Really thanks for this, love the changes, never took so much effort to optimize the build as my main goal was to make 'things work' here but your changes make everything more clear even for future contributors. :smile:

**Pull request merged**
