### PR TITLE
Tidy dockerfile

### PR DESCRIPTION
**Pull request by chrisns**
trims over 100mb (uncompressed) off the docker image

### CODE REVIEW

**Comment by robertsLando** [comment]
@chrisns Just to know, what are main benefits of this changes?

**Comment by chrisns** [comment]
- marginal image size reduction (in the compressed image. more significant when uncompressed)
- remove over optimization in build step layers which means builds are faster from a dev perspective (e.g. no need to checkout openzwave when it fails to compile)

**Comment by robertsLando** [comment]
Ok @chrisns, I saw most Dockerfile are structured using single `RUN` with multiple commands inside and I thought that was the best praticice, I know from a dev prospective it's not so good as if the last command fails you have to restart from first one :\ So it's ok this pr for me. Just wait because If I merge this I stop the other github action that is building the image. Let's see how that goes and then I will merge this.

**Comment by chrisns** [comment]
its best practice to minimize the build steps in general, but because you did a multistep build (having more than one `FROM`) then because all the layers from the prior steps don't get pushed anywhere its totally incidental.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds

**Pull request merged**
